name: CI

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up database
      run: |
        # Commands to set up your test database if required
        # For SQLite, this might be unnecessary
        
    - name: Run unit tests
      run: |
        cd src
        python -m unittest test_app.py

    - name: Run integration tests
      run: |
        pytest src/test_integration.py
